version: '3'

services:

  beobench-rabitmq-broker:
    container_name: beobench-rabitmq-broker
    image: rabbitmq:3
    ports:
      - 5672:5672
    init: true # Faster shutdown.

  beobench-environment-dummy:
    container_name: beobench-environment-dummy
    build:
      context: ./source
      dockerfile: Dockerfile_environment
    init: true # Faster shutdown.
    depends_on: [ "beobench-rabitmq-broker" ]
    environment:
      ENVCONTAINER: 'envcontainer'
  # beobench-agent-dummy:
  #   container_name: beobench-agent-dummy
  #   build:
  #     context: ./source
  #     dockerfile: Dockerfile_agent
  #   init: true # Faster shutdown.
  #   depends_on: [ "beobench-rabitmq-broker" ]
