FROM python:3.10

RUN pip install celery numpy gym

RUN mkdir -p /source/
WORKDIR /source/
COPY __init__.py __init__.py
COPY envwrapper.py envwrapper.py
COPY environment environment

ENTRYPOINT [ "celery", "-A", "envwrapper", "worker", "--loglevel=INFO" ]
